name: Generar Ejecutable JAR

on:
  push:
    branches: [ "main" ]

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Construir JAR con Maven
      # Usamos 'install' para generar el archivo en la carpeta target
      run: mvn clean install -DskipTests

    - name: Subir el archivo JAR como Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sistema-Postulantes-Ejecutable
        path: target/*.jar
